name: array-diff
version: 0.0.1.00

dependencies:
  - base

library:
  exposed-modules: Difference
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - quickcheck
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - array-diff
      - hspec