name: range-extraction
version: 0.0.1.00

dependencies:
  - base

library:
  exposed-modules: RangeExtraction
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - quickcheck
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: angeExtractionSpec.hs
    source-dirs: test
    dependencies:
      - range-extraction
      - hspec