name: count-divisors
version: 0.0.1.00

dependencies:
  - base

library:
  exposed-modules: Divisors
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: DivisorsTest
    source-dirs: test
    dependencies:
      - count-divisors
      - hspec
      - QuickCheck