name: expressions-matter
version: 0.0.1.00

dependencies:
  - base

library:
  exposed-modules: Expression
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - quickcheck
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: ExpressionSpec.hs
    source-dirs: test
    dependencies:
      - expressions-matter
      - hspec