name: expressions-matter
version: 0.0.1.00

dependencies:
  - base

library:
  exposed-modules: Expression
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: ExpressionSpec
    source-dirs: test
    dependencies:
      - expressions-matter
      - QuickCheck
      - hspec